package part1

import (
	"bufio"
	"strings"
	"testing"
)

func TestPart1(t *testing.T) {
	sample := `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`
	reader := strings.NewReader(sample)
	scanner := bufio.NewScanner(reader)
	got := Part1(scanner)
	expected := 21
	if got != expected {
		t.Errorf("Expected %d, got %d", expected, got)
	}
}
